### ISSUE TITLE
"Failed getting access token" error

### ISSUE THREAD

**Issue by kri5t** [intuit/QuickBooks-V3-Java-SDK#126]
We are using this SDK for the quickbooks to host an integration between Pleo and Quickbooks.

For the most part it is working fine, but we keep seeing occasional issues where this error is thrown:

> com.intuit.oauth2.exception.OAuthException: failed getting access token
	at com.intuit.oauth2.client.OAuth2PlatformClient.refreshToken(OAuth2PlatformClient.java:140)

We cannot reproduce it locally and the refresh tokens are working fine. Would it be possible with a more detailed log here?

Like getting some more details from the server describing what is going wrong here? Like is it an outdated token, a revoked token or whatever else can fail.

It is very hard to debug/fix anything from `failed getting access token`.

**Comment by diana-derose** [comment]
Hi @kri5t  - Yes, that makes sense. It looks like the actual response is currently not send back in `BearerTokenResponse`. I'll add it to our backlog to send this back. Will take it up for the next release but feel free to send a PR if you like.

**Comment by shweta-intuitdev** [comment]
Hi @kri5t. The SDK version 6.0.6 now includes more detailed debug logs and additional fields on the OAuthException. Hope this helps.

**Comment by malmyros** [comment]
Hi there, we are actually having a lot of trouble with this. The OAuthException isn't giving us any details of why this is happening or what we should do fix it.

Dependencies:

ipp-v3-java-data-6.0.10.jar
ipp-v3-java-data-6.0.10-sources.jar
ipp-v3-java-devkit-6.0.10-jar-with-dependencies.jar

This is our workflow:

1). System requests for data from quickbooks
2). Request fails because the token has expired
3). We then use OAuth2PlatformClient.refresToken to update the token
4). At this point we receive an exception:

Error Code: 400,Error Message: failed getting access token

Could you please elaborate a bit more of what needs to happen here?
