### ISSUE TITLE
Security vulnerability on ipp-java-qbapihelper@5.0.5

### ISSUE THREAD

**Issue by honsq90** [intuit/QuickBooks-V3-Java-SDK#55]
Hello! We received a vulnerability check on the following.

Seems like org.openid4java:openid4java@1.0.0 is available but I'm not sure if that'll fix the xerces:xercesImpl version.

```
✗ High severity vulnerability found in xerces:xercesImpl
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-JAVA-XERCES-31585
  Introduced through: com.intuit.quickbooks-online:ipp-java-qbapihelper@5.0.5
  From: com.intuit.quickbooks-online:ipp-java-qbapihelper@5.0.5 > org.openid4java:openid4java@0.9.8 > xerces:xercesImpl@2.8.1
```

**Comment by diana-derose** [comment]
Hi @honsq90  - Are you still using OpendId2.0 or OAuth1? If not, just remove that artifact from your project. We will be deprecating this artifact soon since Intuit has already deprecated OpenID2.0 and OAuth1 will also be deprecated later this year. 
If the above doesn't work for you, just override it in your pom by adding a higher version of xerces xerces:xercesImpl:2.12.0 externally.

**Comment by honsq90** [comment]
will be moving to OAuth2 soon. will override it in that case. cheers :)
